def Student(n,a,m1,m2,m3,m4,m5):
    print("\nNAME --> ",n)
    print("AGE --> ",a)
    print("MARK 1 --> ",m1)
    print("MARK 2 --> ",m2)
    print("MARK 3 --> ",m3)
    print("MARK 4 --> ",m4)
    print("MARK 5 --> ",m5)
name=input("ENTER THE NAME --> ")
age=int(input("ENTER THE AGE --> "))
mark1=int(input("ENTER MARK 1 --> "))
mark2=int(input("ENTER MARK 2 --> "))
mark3=int(input("ENTER MARK 3 --> "))
mark4=int(input("ENTER MARK 4 --> "))
mark5=int(input("ENTER MARK 5 --> "))
Student(name,age,mark1,mark2,mark3,mark4,mark5)
